Revisited scripts around asenv
- Backported "in advance" from future 7.1 branch and rewritten to reduce
  duplication and to fix all related issues.
- All linux scripts use bash now
- All scripts use the same way of AS_INSTALL resolution
- Removed mentions about Java 1.6
- Fixed %t resolving on Windows (ie JDK log formatting option) which has to be
  escaped.
- Added config.sh script sourced by all bash scripts
  - Loads asenv.conf
  - Sets AS_INSTALL
- AS_INSTALL removed from asenv.conf
  - it doesn't make sense here
  - it overrides values set in scripts
  - it was just a relative path

Signed-off-by: David Matějček <david.matejcek@omnifish.ee>

diff --git a/appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/appclient b/appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/appclient
--- a/appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/appclient
+++ b/appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/appclient
@@ -1,5 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 #
+# Copyright (c) 2024, 2025 Contributors to the Eclipse Foundation
 # Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 #
 # This program and the accompanying materials are made available under the
@@ -15,64 +16,7 @@
 # SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 #
 
-# 
-
-# set -x
-
-chooseJava() {
-#
-# Looks for Java at AS_JAVA, JAVA_HOME or in the path.
-# Sets javaSearchType to tell which was used to look for java,
-# javaSearchTarget to the location (or path), and
-# JAVA to the found java executable.
-#
-# If the user specifies AS_JAVA or JAVA_HOME record that setting
-# to be passed as a property to the bootstrap program.
-#
-    # Depends upon Java from ../config/asenv.conf
-    if [ "${AS_JAVA}" != "" ]; then
-        javaSearchType=AS_JAVA
-        javaSearchTarget="$AS_JAVA"
-        JAVA="${AS_JAVA}/bin/java"
-    elif [ "${JAVA_HOME}" != "" ]; then
-        javaSearchType=JAVA_HOME
-        javaSearchTarget="$JAVA_HOME"
-        JAVA="${JAVA_HOME}/bin/java"
-    else
-        # Look in the PATH.
-        seekJavaOnPath
-        javaSearchType=PATH
-        javaSearchTarget=$PATH
-    fi
-#
-# Make sure java really exists where we were told to look.  If not
-# display how we tried to find it and then try to run it, letting the shell
-# issue the error so we don't have to do i18n of our own message from the script.
-
-    if [ ! -x "${JAVA}" ]; then
-        echo
-        echo $javaSearchType=$javaSearchTarget
-        echo
-        ${JAVA}
-        exit
-    fi
-ACCJava="${JAVA}"
-export ACCJava
-}
-
-seekJavaOnPath() {
-        JAVA=`which java`
-}
-
-
-_AS_INSTALL=`dirname "$0"`/..
-export _AS_INSTALL
-case "`uname`" in
-  CYGWIN*) _AS_INSTALL=`cygpath --windows $_AS_INSTALL`
-           cygwinProp=-Dorg.glassfish.isCygwin=true
-esac
-. "${_AS_INSTALL}/config/asenv.conf"
-
-chooseJava
-
-eval "`"${ACCJava}" -Dorg.glassfish.appclient.shell $cygwinProp -classpath "${_AS_INSTALL}/lib/gf-client.jar" org.glassfish.appclient.client.CLIBootstrap "$@"`"
+AS_CONFIG="$(dirname "$(realpath -s "$0")")/../config"
+AS_CONFIG_SH="${AS_CONFIG}/config.sh"
+source "${AS_CONFIG_SH}" "$AS_CONFIG" || { echo "${AS_CONFIG_SH} not found" >&2; exit 1; }
+eval "`"${JAVA}" -Dorg.glassfish.appclient.shell $cygwinProp -classpath "${AS_INSTALL}/lib/gf-client.jar" org.glassfish.appclient.client.CLIBootstrap "$@"`"
diff --git a/appserver/distributions/glassfish-common/src/main/resources/bin/debug-asadmin b/appserver/distributions/glassfish-common/src/main/resources/bin/debug-asadmin
--- a/appserver/distributions/glassfish-common/src/main/resources/bin/debug-asadmin
+++ b/appserver/distributions/glassfish-common/src/main/resources/bin/debug-asadmin
@@ -1,5 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 #
+# Copyright (c) 2024, 2025 Contributors to the Eclipse Foundation
 # Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
 #
 # This program and the accompanying materials are made available under the
@@ -15,15 +16,7 @@
 # SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 #
 
-# Always use JDK 1.6 or higher
-AS_INSTALL=`dirname "$0"`/../glassfish
-AS_INSTALL_LIB="$AS_INSTALL/lib"
-. "${AS_INSTALL}/config/asenv.conf"
-JAVA=java
-#Depends upon Java from ../config/asenv.conf
-if [ ${AS_JAVA} ]; then
-    JAVA=${AS_JAVA}/bin/java
-fi
-
-exec "$JAVA" -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=9008 -jar "$AS_INSTALL_LIB/client/appserver-cli.jar" "$@"
-
+AS_CONFIG="$(dirname "$(realpath -s "$0")")/../glassfish/config"
+AS_CONFIG_SH="${AS_CONFIG}/config.sh"
+source "${AS_CONFIG_SH}" "$AS_CONFIG" || { echo "${AS_CONFIG_SH} not found" >&2; exit 1; }
+exec "$JAVA" -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=9008 -jar "$AS_INSTALL/lib/client/appserver-cli.jar" "$@"
