startserv script didn't work if path contained spaces
E.g. if GlassFish installed in /path/to/with spaces/glassfish

Needed to add '' around each argument and run it using eval apply the quotes, simple exec would ignore the quotes.

Also added some simple clean up of code without functional changes.

(cherry picked from commit f501a00733ee42feec76290379acc595682a93d8)

diff --git a/appserver/distributions/glassfish-common/src/main/resources/bin/startserv b/appserver/distributions/glassfish-common/src/main/resources/bin/startserv
--- a/appserver/distributions/glassfish-common/src/main/resources/bin/startserv
+++ b/appserver/distributions/glassfish-common/src/main/resources/bin/startserv
@@ -16,9 +16,9 @@
 # SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 #
 
-startAsMainProcess() {
+startAsMainProcess () {
     if [[ "$@" == "--help" ]] || [[ "$@" == "--help=true" ]] || [[ "$@" == "-?" ]]; then
-      exec "$JAVA" ${ASADMIN_JVM_OPTIONS} --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" org.glassfish.admin.cli.AsadminMain start-domain --help
+      exec "$JAVA" ${ASADMIN_JVM_OPTIONS} --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" com.sun.enterprise.admin.cli.AdminMain start-domain --help
     fi
 
     # Execute start-domain --dry-run and store the output line by line into an array.
@@ -28,7 +28,7 @@ startAsMainProcess() {
     local DRY_RUN_OUTPUT=()
     local SKIP_LINES_UNTIL_DUMP=y
     local DRY_RUN_OUTPUT_BEFORE_DUMP=
-    while read COM; do
+    while IFS= read -r COM; do
       if [[ "$SKIP_LINES_UNTIL_DUMP" == y ]]; then
         if [[ "$COM" == Dump* ]]; then
           SKIP_LINES_UNTIL_DUMP=n
@@ -36,11 +36,10 @@ startAsMainProcess() {
           DRY_RUN_OUTPUT_BEFORE_DUMP+="$COM\n";
         fi
       else
-        DRY_RUN_OUTPUT+=("$COM");
+        DRY_RUN_OUTPUT+=("'$COM'");
       fi
-    done < <("$JAVA" ${ASADMIN_JVM_OPTIONS} --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" org.glassfish.admin.cli.AsadminMain start-domain --dry-run "$@" || echo "FAILED")
-    if [[ x"$DRY_RUN_OUTPUT" == x ]]
-      then
+    done < <("$JAVA" ${ASADMIN_JVM_OPTIONS} --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" com.sun.enterprise.admin.cli.AdminMain start-domain --dry-run "$@" || echo "FAILED")
+    if [[ ${#DRY_RUN_OUTPUT[@]} -eq 0 ]]; then
         echo -n -e "${DRY_RUN_OUTPUT_BEFORE_DUMP}" >&2
         exit 1
     fi
@@ -49,14 +48,13 @@ startAsMainProcess() {
     # If all OK, execute the command to start GlassFish.
     # Remove the last line as it's not part of the command.
     local FINAL_COMMAND=(${DRY_RUN_OUTPUT[@]:0:${OUTPUT_LENGTH}-2})
-    exec "${FINAL_COMMAND[@]}"
+    eval "exec ${FINAL_COMMAND[@]}"
 
 }
 
 AS_CONFIG="$(dirname "$(realpath "$0")")/../glassfish/config"
 AS_CONFIG_SH="${AS_CONFIG}/config.sh"
 source "${AS_CONFIG_SH}" "$AS_CONFIG" || { echo "${AS_CONFIG_SH} not found" >&2; exit 1; }
-export ASADMIN_CLASSPATH="$AS_INSTALL/appserver-cli.jar:${ASADMIN_CLASSPATH}"
 startAsMainProcess "$@"
 
 # Alternatively, run the following:
