Move startserv and stopserv scripts from nucleus to glassfish-common
Scripts in glassfish-common use org.glassfish.admin.cli.AsadminMain while nadmin in nucleus uses com.sun.enterprise.admin.cli.AdminMain

(cherry picked from commit 00186b26a832f1bf7ac7fca1e4bac983f1ba7071)

diff --git a/appserver/distributions/glassfish-common/src/main/resources/bin/startserv b/appserver/distributions/glassfish-common/src/main/resources/bin/startserv
--- a/appserver/distributions/glassfish-common/src/main/resources/bin/startserv
+++ b/appserver/distributions/glassfish-common/src/main/resources/bin/startserv
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (c) 2023, 2025 Contributors to the Eclipse Foundation
+# Copyright (c) 2023, 2026 Contributors to the Eclipse Foundation
 # Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 #
 # This program and the accompanying materials are made available under the
@@ -18,7 +18,7 @@
 
 startAsMainProcess () {
     if [[ "$@" == "--help" ]] || [[ "$@" == "--help=true" ]] || [[ "$@" == "-?" ]]; then
-      exec "$JAVA" ${ASADMIN_JVM_OPTIONS} --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" com.sun.enterprise.admin.cli.AdminMain start-domain --help
+      exec "$JAVA" ${ASADMIN_JVM_OPTIONS} --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" org.glassfish.admin.cli.AsadminMain start-domain --help
     fi
 
     # Execute start-domain --dry-run and store the output line by line into an array.
@@ -38,7 +38,7 @@ startAsMainProcess () {
       else
         DRY_RUN_OUTPUT+=("'$COM'");
       fi
-    done < <("$JAVA" ${ASADMIN_JVM_OPTIONS} --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" com.sun.enterprise.admin.cli.AdminMain start-domain --dry-run "$@" || echo "FAILED")
+    done < <("$JAVA" ${ASADMIN_JVM_OPTIONS} --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" org.glassfish.admin.cli.AsadminMain start-domain --dry-run "$@" || echo "FAILED")
     if [[ ${#DRY_RUN_OUTPUT[@]} -eq 0 ]]; then
         echo -n -e "${DRY_RUN_OUTPUT_BEFORE_DUMP}" >&2
         exit 1
@@ -55,6 +55,7 @@ startAsMainProcess () {
 AS_CONFIG="$(dirname "$(realpath "$0")")/../glassfish/config"
 AS_CONFIG_SH="${AS_CONFIG}/config.sh"
 source "${AS_CONFIG_SH}" "$AS_CONFIG" || { echo "${AS_CONFIG_SH} not found" >&2; exit 1; }
+export ASADMIN_CLASSPATH="$AS_INSTALL/appserver-cli.jar:${ASADMIN_CLASSPATH}"
 startAsMainProcess "$@"
 
 # Alternatively, run the following:
