Fixed classpaths and env variables
- AS_INSTALL must be absolute env option despite it can be also autodetected,
  but then it would not be possible to use it in scripts (chicken-egg problem).
- classpaths in manifests sometimes don't work on JDK11-17, not sure why
  exactly.

Signed-off-by: David Matějček <david.matejcek@omnifish.ee>

diff --git a/nucleus/distributions/nucleus-common/src/main/resources/bin/startserv b/nucleus/distributions/nucleus-common/src/main/resources/bin/startserv
--- a/nucleus/distributions/nucleus-common/src/main/resources/bin/startserv
+++ b/nucleus/distributions/nucleus-common/src/main/resources/bin/startserv
@@ -16,23 +16,20 @@
 # SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 #
 
-AS_INSTALL=`dirname "$0"`/..
+export AS_INSTALL="$(dirname $(realpath -s $0))/.."
 case "`uname`" in
   CYGWIN*) AS_INSTALL=`cygpath --windows $AS_INSTALL`
 esac
 . "${AS_INSTALL}/config/asenv.conf"
 
 JAVA=java
-#Depends upon Java from ../config/asenv.conf
 if [ ${AS_JAVA} ]; then
     JAVA=${AS_JAVA}/bin/java
 fi
 
-ASADMIN_CLASSPATH="$AS_INSTALL/admin-cli.jar:$AS_INSTALL/modules/*"
-
 start_as_main_process () {
     if [[ "$@" == "--help" ]] || [[ "$@" == "--help=true" ]] || [[ "$@" == "-?" ]]; then
-      exec "$JAVA" "${ASADMIN_JVM_OPTIONS}" --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" com.sun.enterprise.admin.cli.AdminMain start-domain --help
+      exec "$JAVA" ${ASADMIN_JVM_OPTIONS} --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" com.sun.enterprise.admin.cli.AdminMain start-domain --help
     fi
 
     # Execute start-domain --dry-run and store the output line by line into an array.
@@ -52,7 +49,7 @@ start_as_main_process () {
       else
         DRY_RUN_OUTPUT+=("$COM");
       fi
-    done < <("$JAVA" "${ASADMIN_JVM_OPTIONS}" --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" com.sun.enterprise.admin.cli.AdminMain start-domain --dry-run "$@" || echo "FAILED")
+    done < <("$JAVA" ${ASADMIN_JVM_OPTIONS} --module-path "${ASADMIN_MODULEPATH}" --add-modules ALL-MODULE-PATH -cp "$ASADMIN_CLASSPATH" com.sun.enterprise.admin.cli.AdminMain start-domain --dry-run "$@" || echo "FAILED")
     if [[ x"$DRY_RUN_OUTPUT" == x ]]
       then
         echo -n -e "${DRY_RUN_OUTPUT_BEFORE_DUMP}" >&2
